### ISSUE TITLE
Memory consumption explodes when using mappability tracks

### ISSUE THREAD

**Issue by mxenoph** [AndreasHeger/gat#2]
Hi,

Running GAT with just regions that are not assembly gaps finishes in a few seconds without large memory requirements, however passing uniquely mappable regions as an additional workspace causes the program to crash due to insufficient memory. I have increased the memory passed to GAT to tens of GB and it still exits due to memory requirements.  (I run the following command on a cluster allowing maximum of 100GB memory and reserving at least 40GB)

```bash
gat-run.py --segments=M2_pooled_filtered_peaks.bed 
 --annotations=annotations.bed 
 --workspace=contigs_ungapped.bed 
--workspace=MM10-mappability_50.bed
--output-counts-pattern=M2_pooled_filtered_%s.overlap.counts.tsv.gz 
--num-threads 8 --num-samples=10000 --log=gat.log --pvalue-method=norm > M2_pooled_filtered_gat.tsv
```

I am not entirely convinced that I correctly retrieve the uniquely mappable regions so it would be great if you can summarise how you derived that from the UCSC mappability tracks. I am working with mm10, for which UCSC doesn't have mappability tracks so I am using `gem-mappability` to produce them for  50bp reads. The output (which I convert to wig and then bed) gives me around 8 million intervals (probably the reason GAT crashes!) with a score of 1 (uniquely mappable). If I understand mappability tracks correctly any kmer starting within the reported interval is unique, so I extend the region's end by 50bp.

Could you please provide `mapability_36.filtered.bed.gz` file you use in the tutorials (https://media.readthedocs.org/pdf/gat/latest/gat.pdf) as an example? Have you done any tests on how big the workspace and annotation can be without memory requirements getting huge?

Many thanks for your help.

P.S.: `M2_pooled_filtered_peaks.bed`  and `annotations.bed` are 43492 and 4707 intervals, respectively.

**Comment by AndreasHeger** [comment]
Hi, typically the memory problem occurs if a workspace is provided that contains 4 BED columns where the fourth bed column is some form of label. For example::

```
chr1 10   100  region1
chr1  2000 3000 region2
```

while the intention is likely that these regions belong to the same workspace, GAT will treat these as individual and compute samples separately. This causes the memory to explode, especially if there are
many such regions. Can you please check if that is the case in your bed files you supply as the workspace? Best they should contain only 3 columns or if they contain 4 the fourth column should be identical throughout.

Some gat datasets are here:

https://www.cgat.org/downloads/public/gat/datasets/

I will see if we have an mm10 somewhere.

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
Closing for now.

**Comment by selomics** [comment]
Hi, do any of you have mm10 mappability track file somewhere that I can download?. 

Any help is appreciated since it's not publicly available to my knowledge.

**Comment by AndreasHeger** [comment]
Sorry, I don't think we have it at the moment.

Best wishes,
Andreas
