### ISSUE TITLE
Feature request: gat-compare should not assume the "track" column is equal to "merged"

### ISSUE THREAD

**Issue by skiaphrene** [AndreasHeger/gat#3]
Dear Andreas,

I have been happily using GAT (gat-run & gat-compare) over the past months - thanks a lot for it!

I recently updated all of my code so that I could keep a more informative string in the "track" column in my gat-run output. However, when I got to gat-compare I no longer got any results. Inspecting the code it seems that the things around lines 264-270 of gat-compare, the code assumes that the "track" column only contains the string "merged". This would be the case when using --ignore-segment-tracks as I was doing previously, but now with my more "informative" track strings, this blocks things.

Would it be possible to add to the code so that - similar to what is done in the in-file-comparison part - the list of track values is established and iterated over, to remove this hard-coded limitation?

Thank you in advance for your help!

Best regards,

-- Alex

**Comment by AndreasHeger** [comment]
@skiaphrene , thanks, add this to the next version.
