### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by imk1** [AndreasHeger/gat#5]
I just installed GAT and tried running gat-run.py.  I immediately got this error:
Traceback (most recent call last):
  File "../scripts/gat-run.py", line 73, in <module>
    import gat.SegmentList as SegmentList
ImportError: No module named SegmentList

SegmentList.pyx is in gat/gat, so I am not sure why this is happening.  Might someone be able to help me out?  Thanks!

**Comment by foriin** [comment]
Can someone elaborate what to do in this case? No answer and I Have the same problem with GatEngine and SegmentList
